### ISSUE TITLE
Feature: Allow customized headers and proxy for requests

### ISSUE THREAD

**Issue by DDEle** [bitomic/mwjs#158]
It seems that only `jarOptions` are allowed when creating a `RequestManager` to feed `new Wiki()` currently.

**Comment by bitomic** [comment]
I am not too familiar with proxies, but accordingly to [node-fetch#options](https://github.com/node-fetch/node-fetch#options), it can be accomplished through the `agent` property in the `RequestInit` object. edef50f should address it, I think? 

Published as `mw.js@2.2.0`. Let me know if there's any problem with it, otherwise I will close the issue. 😄

**Comment by DDEle** [comment]
Big thanks for your quick response! It looks good to me now except that currently `RequestManager` is not exported. I guess you need to add `export * from './utils';` to `main.ts`.

**Comment by bitomic** [comment]
Absolutely my bad, didn't notice it wasn't exported (even when it is in the optional constructor parameters of `Wiki` since pretty much ever, haha). Fixed in 3bd22ea and published as `mw.js@2.2.1`.

**Comment by DDEle** [comment]
Thanks for the fix!
